### ISSUE TITLE
add some way to allow me to debug / print out each asset as it is loaded 

### ISSUE THREAD

**Issue by ethereumdegen** [NiklasEi/bevy_asset_loader#248] opened 2024-12-06 16:53 UTC
add some way to allow me to debug / print out each asset as it is loaded 

i get an error Handle type doesnt match the typeid of this untyped handle 

but i cant figure out which of my files being loaded is improper !

**Comment by NiklasEi** [comment] 2024-12-07 21:57
To check when a collection is loaded, you can request the collections as optional resources. It's not ideal, I agree, but that is all that is currently possible.

I've been thinking about a major restructuring using observers that might help with that in the future.

Closing as duplicate of  #108

**Closed by NiklasEi** 2024-12-07 21:57 UTC
