### ISSUE TITLE
Loading GLTF animations individually

### ISSUE THREAD

**Issue by Sheepyhead** [NiklasEi/bevy_asset_loader#168] opened 2023-12-04 10:40 UTC
Hey there. I'm trying to load animations from a GLTF file, and I have confirmed that it has five animations with real durations by loading the whole Gltf asset, but when I try to load it with bevy_asset_loader I get an error that the asset registers as AssetUntyped, not AnimationClip. The asset collection looks like this, I have several other types of assets that load just fine. Glb file attached.

[CharacterAnimations.zip](https://github.com/NiklasEi/bevy_asset_loader/files/13544889/CharacterAnimations.zip)

```rs
#[derive(AssetCollection, Resource)]
pub struct AnimationAssets {
    #[asset(path = "animations/CharacterAnimations.glb#Animation0")]
    pub attack: Handle<AnimationClip>,

    #[asset(path = "animations/CharacterAnimations.glb#Animation1")]
    pub death: Handle<AnimationClip>,

    #[asset(path = "animations/CharacterAnimations.glb#Animation2")]
    pub hit: Handle<AnimationClip>,

    #[asset(path = "animations/CharacterAnimations.glb#Animation3")]
    pub idle: Handle<AnimationClip>,

    #[asset(path = "animations/CharacterAnimations.glb#Animation4")]
    pub run: Handle<AnimationClip>,
}

**Comment by NiklasEi** [comment] 2023-12-09 09:20
I'll take a look. Have you tried to recreate this issue in Bevy? This plugin has no logic concerning asset path labels or animations, so this might be a Bevy issue.

**Comment by NiklasEi** [comment] 2023-12-11 22:41
You need to run `cargo update`. This was broken in Bevy `0.12.0` and fixed with the last patch release.

**Comment by NiklasEi** [comment] 2023-12-12 12:05
I saw that you mentioned, on Discord that you can load `Scene` without issues. That would speak against the problem from `0.12.0`. Could you verify your Bevy version please?

I can load the following collection in `0.12.1`
```rust
#[derive(AssetCollection, Resource)]
struct MyAssets {
    #[asset(path = "CharacterAnimations.glb#Animation0")]
    player: Handle<AnimationClip>,
}
```

**Comment by NiklasEi** [comment] 2023-12-12 12:07
I do get a bunch of warnings though: `WARN bevy_gltf::loader: Animation interpolation Step is not supported, will use linear`

**Comment by NiklasEi** [comment] 2023-12-27 16:30
@Sheepyhead Do you have any more information on this? I am unable to reproduce the issue with Bevy `0.12.1` so far.

**Comment by Sheepyhead** [comment] 2024-01-14 12:50
Yes hi, sorry for the delay, I tried cargo update, and now  I get a lot of the warnings you mention while it loads, but now I just get a black screen instead of seeing the 3d assets that loads fine without loading the animations (I'm not even using the animations for anything yet) so there's still something weird going on. I'll investigate the handles and write back

**Comment by NiklasEi** [comment] 2024-04-13 15:02
I cannot reproduce this with latest Bevy so I will close this issue for now. Please feel free to re-open if it persists for you.

**Closed by NiklasEi** 2024-04-13 15:02 UTC
