### ISSUE TITLE
Full example crashes at typed + mapped values

### ISSUE THREAD

**Issue by janhohenheim** [NiklasEi/bevy_asset_loader#104] opened 2023-02-05 05:25 UTC
When using both `typed` and `mapped`, a folder is expected to be of the form "foo/bar": https://github.com/NiklasEi/bevy_asset_loader/blob/9a7966c9e7a44026a2192292390b315d28c88ca7/bevy_asset_loader_derive/src/assets.rs#L156
ut the examples don't do this: https://github.com/NiklasEi/bevy_asset_loader/blob/9a7966c9e7a44026a2192292390b315d28c88ca7/bevy_asset_loader/examples/full_collection.rs#L48

As a side note, I cannot get the feature showcased in the linked line in the example to work at all in my projects. Does it currently work at all or am I simply missing something?

**Comment by NiklasEi** [comment] 2023-02-05 11:36
The first line is acting on paths of the files inside the folder, which all have a path like `folder/file`. The example might have been broken because I hard-coded the file separator `/`. Could you try the example again, please?
The `typed` property is only available on `main`. It will be in the next release :slightly_smiling_face:

**Comment by janhohenheim** [comment] 2023-02-05 15:17
The fix you propose can't be the cause since I am on macOS. With the current `main`, I still get the following error:
```
thread 'main' panicked at 'Should be a folder', bevy_asset_loader\examples/full_collection.rs:20:10
```
I am also using the `main` branch in my own tests, but for some reason I can only get the following form  to work:
```rust
#[asset(paths("folder/file_a", "folder/file_b"), collection(typed, mapped))]
```
instead of the simpler:
```rust
#[asset(path("folder"), collection(typed, mapped))]
```

**Comment by NiklasEi** [comment] 2023-02-24 22:14
Can you please verify that the issue is resolved on the latest main?

**Closed** 2023-02-24 22:13 UTC

**Comment by janhohenheim** [comment] 2023-02-24 22:35
Thanks for the fix! Getting the "Everything looks good!" message on `main`, testing a real world application now...
